//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.UserBranches = new HashSet<UserBranch>();
        }
    
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public string PhoneNumber { get; set; }
        public string ManagerName { get; set; }
        public string ZipCode { get; set; }
        public string BranchAddress { get; set; }
        public Nullable<long> ClientID { get; set; }
        public Nullable<long> BranchNum { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBranch> UserBranches { get; set; }
    }
}
