//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Branches = new HashSet<Branch>();
            this.tb_send = new HashSet<tb_send>();
        }
    
        public long ID { get; set; }
        public string ClientID { get; set; }
        public string PublicKey { get; set; }
        public string PrivateKey { get; set; }
        public string Econo { get; set; }
        public string ParticipationID { get; set; }
        public Nullable<long> TraceCode { get; set; }
        public string Tins { get; set; }
        public Nullable<long> PersonId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch> Branches { get; set; }
        public virtual tb_person tb_person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_send> tb_send { get; set; }
    }
}
