//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentPost_TB
    {
        public long comment_post_ID { get; set; }
        public string matn { get; set; }
        public Nullable<long> userid { get; set; }
        public Nullable<long> postid { get; set; }
        public Nullable<bool> act { get; set; }
    
        public virtual Post_TB Post_TB { get; set; }
        public virtual user_TB user_TB { get; set; }
    }
}
