//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInPerson
    {
        public long ContactInPersonID { get; set; }
        public Nullable<long> personID { get; set; }
        public Nullable<long> ContactID { get; set; }
    
        public virtual tb_contact tb_contact { get; set; }
        public virtual tb_person tb_person { get; set; }
    }
}
