//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fav_TB
    {
        public long favID { get; set; }
        public Nullable<long> LocID { get; set; }
        public Nullable<long> userID { get; set; }
        public Nullable<bool> balad { get; set; }
    
        public virtual Locations_TB Locations_TB { get; set; }
        public virtual user_TB user_TB { get; set; }
    }
}
