//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBooking
    {
        public long Id { get; set; }
        public long HotelId { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string NationalCode { get; set; }
        public string NationalCard { get; set; }
        public int TripperCount { get; set; }
        public System.DateTime FromDate { get; set; }
        public string FromDateFa { get; set; }
        public System.DateTime ToDate { get; set; }
        public string ToDateFa { get; set; }
        public long Amount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<long> TransactionId { get; set; }
    
        public virtual BookingStatu BookingStatu { get; set; }
        public virtual BookingTransaction BookingTransaction { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual User User { get; set; }
    }
}
