//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceBody
    {
        public long InvoiceBodyID { get; set; }
        public Nullable<long> Taxid { get; set; }
        public Nullable<long> Sstid { get; set; }
        public Nullable<decimal> Am { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<decimal> Cfee { get; set; }
        public string Cut { get; set; }
        public Nullable<decimal> Exr { get; set; }
        public Nullable<decimal> Prdis { get; set; }
        public Nullable<decimal> Dis { get; set; }
        public Nullable<decimal> Adis { get; set; }
        public Nullable<decimal> Vra { get; set; }
        public Nullable<decimal> Vam { get; set; }
        public string Odt { get; set; }
        public Nullable<decimal> Odr { get; set; }
        public Nullable<decimal> Odam { get; set; }
        public string Olt { get; set; }
        public Nullable<decimal> Olr { get; set; }
        public Nullable<decimal> Olam { get; set; }
        public Nullable<decimal> Concfee { get; set; }
        public Nullable<decimal> Spro { get; set; }
        public Nullable<decimal> Bros { get; set; }
        public Nullable<decimal> Tcpbs { get; set; }
        public Nullable<decimal> Vop { get; set; }
        public string Sstt { get; set; }
        public Nullable<int> MuS { get; set; }
        public Nullable<decimal> Tsstam { get; set; }
        public string Bsrn { get; set; }
        public Nullable<decimal> Cop { get; set; }
    
        public virtual InvoiceHeader InvoiceHeader { get; set; }
    }
}
