//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceField
    {
        public int ID { get; set; }
        public string InvoiceTitle { get; set; }
        public Nullable<int> FieldPositionID { get; set; }
        public string Field { get; set; }
        public string InvoiceTitleEn { get; set; }
        public Nullable<int> Inp11 { get; set; }
        public Nullable<int> Inp12 { get; set; }
        public Nullable<int> Inp13 { get; set; }
        public Nullable<int> Inp14 { get; set; }
        public Nullable<int> Inp15 { get; set; }
        public Nullable<int> Inp16 { get; set; }
        public Nullable<int> Inp17 { get; set; }
        public Nullable<int> inp21 { get; set; }
        public Nullable<int> inp22 { get; set; }
        public Nullable<int> inp31 { get; set; }
    
        public virtual OptionalMode OptionalMode { get; set; }
        public virtual OptionalMode OptionalMode1 { get; set; }
        public virtual OptionalMode OptionalMode2 { get; set; }
        public virtual OptionalMode OptionalMode3 { get; set; }
        public virtual OptionalMode OptionalMode4 { get; set; }
        public virtual OptionalMode OptionalMode5 { get; set; }
        public virtual OptionalMode OptionalMode6 { get; set; }
        public virtual OptionalMode OptionalMode7 { get; set; }
        public virtual OptionalMode OptionalMode8 { get; set; }
        public virtual OptionalMode OptionalMode9 { get; set; }
    }
}
