//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.LocationComments = new HashSet<LocationComment>();
            this.LocationImages = new HashSet<LocationImage>();
            this.TourStops = new HashSet<TourStop>();
            this.Users = new HashSet<User>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int TypeId { get; set; }
        public int Weight { get; set; }
        public int ProvinceId { get; set; }
        public int CityId { get; set; }
        public string Village { get; set; }
        public string Attractions { get; set; }
        public string Facilities { get; set; }
        public string Accessibility { get; set; }
        public bool IsActive { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> OldLocationId { get; set; }
    
        public virtual LocCity LocCity { get; set; }
        public virtual LocationType LocationType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationComment> LocationComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationImage> LocationImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourStop> TourStops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
