//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreTerminalSystemEntities : DbContext
    {
        public StoreTerminalSystemEntities()
            : base("name=StoreTerminalSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<CompanyType> CompanyTypes { get; set; }
        public virtual DbSet<ContactInPerson> ContactInPersons { get; set; }
        public virtual DbSet<Curreny> Currenies { get; set; }
        public virtual DbSet<ErrorCode> ErrorCodes { get; set; }
        public virtual DbSet<ErrorType> ErrorTypes { get; set; }
        public virtual DbSet<FieldPosition> FieldPositions { get; set; }
        public virtual DbSet<ftType> ftTypes { get; set; }
        public virtual DbSet<InPatern> InPaterns { get; set; }
        public virtual DbSet<InsType> InsTypes { get; set; }
        public virtual DbSet<InType> InTypes { get; set; }
        public virtual DbSet<InvoiceBody> InvoiceBodies { get; set; }
        public virtual DbSet<InvoiceField> InvoiceFields { get; set; }
        public virtual DbSet<InvoiceHeader> InvoiceHeaders { get; set; }
        public virtual DbSet<muType> muTypes { get; set; }
        public virtual DbSet<OptionalMode> OptionalModes { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PersonType> PersonTypes { get; set; }
        public virtual DbSet<pmtType> pmtTypes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<SpecialOrGeneral> SpecialOrGenerals { get; set; }
        public virtual DbSet<TaxableOrFree> TaxableOrFrees { get; set; }
        public virtual DbSet<tb_bank> tb_bank { get; set; }
        public virtual DbSet<tb_check_send> tb_check_send { get; set; }
        public virtual DbSet<tb_contact> tb_contact { get; set; }
        public virtual DbSet<tb_degree> tb_degree { get; set; }
        public virtual DbSet<tb_magor> tb_magor { get; set; }
        public virtual DbSet<tb_marketing> tb_marketing { get; set; }
        public virtual DbSet<tb_person> tb_person { get; set; }
        public virtual DbSet<tb_send> tb_send { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserBranch> UserBranches { get; set; }
    }
}
