//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long pmtID { get; set; }
        public Nullable<long> Taxid { get; set; }
        public Nullable<System.DateTime> pdt { get; set; }
        public Nullable<long> PaymentInstrumentID { get; set; }
        public string Iinn { get; set; }
        public string Acn { get; set; }
        public string Trmn { get; set; }
        public string Trn { get; set; }
        public string Pcn { get; set; }
        public string Pid { get; set; }
        public Nullable<int> SetmID { get; set; }
    
        public virtual InvoiceHeader InvoiceHeader { get; set; }
    }
}
