//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.PaymentResults = new HashSet<PaymentResult>();
        }
    
        public long Id { get; set; }
        public long TransactionId { get; set; }
        public long Amount { get; set; }
        public bool IsPaid { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime PayDate { get; set; }
        public bool InApp { get; set; }
    
        public virtual BookingTransaction BookingTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentResult> PaymentResults { get; set; }
    }
}
