//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post_TB()
        {
            this.CommentPost_TB = new HashSet<CommentPost_TB>();
        }
    
        public long postid { get; set; }
        public string title { get; set; }
        public string matn { get; set; }
        public Nullable<long> userid { get; set; }
        public Nullable<bool> act { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ImageUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentPost_TB> CommentPost_TB { get; set; }
        public virtual user_TB user_TB { get; set; }
    }
}
