//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ProductID { get; set; }
        public long sstid { get; set; }
        public string Date { get; set; }
        public Nullable<int> Vat { get; set; }
        public Nullable<int> VatCustomPurposes { get; set; }
        public string sstt { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> SpecialOrGeneralID { get; set; }
        public Nullable<int> TaxableOrFreeID { get; set; }
        public Nullable<int> mu { get; set; }
    
        public virtual muType muType { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual SpecialOrGeneral SpecialOrGeneral { get; set; }
        public virtual TaxableOrFree TaxableOrFree { get; set; }
    }
}
