//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_check_send
    {
        public long SendCheckId { get; set; }
        public string Response { get; set; }
        public string CheckResponse { get; set; }
        public string CheckDate { get; set; }
        public Nullable<long> SendId { get; set; }
        public Nullable<int> state { get; set; }
        public string UID { get; set; }
        public string ReferenceNumber { get; set; }
        public string invoiceData { get; set; }
        public string ResponseStatus { get; set; }
    
        public virtual tb_send tb_send { get; set; }
    }
}
