//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_marketing
    {
        public long MarketingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string NationalCode { get; set; }
        public string title { get; set; }
        public string note { get; set; }
        public string RegDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
