//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_person()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public long PersonID { get; set; }
        public string NatioinalCode { get; set; }
        public Nullable<int> PersonTypeId { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string FatherName { get; set; }
        public string BirthDate { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string ComapnyName { get; set; }
        public string Zipcode { get; set; }
        public string RegisterationDate { get; set; }
        public Nullable<int> CompanyTypeId { get; set; }
        public string RegisterNumber { get; set; }
        public Nullable<int> BankID { get; set; }
        public string Shaba { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
        public virtual CompanyType CompanyType { get; set; }
        public virtual ContactInPerson ContactInPerson { get; set; }
        public virtual PersonType PersonType { get; set; }
        public virtual tb_bank tb_bank { get; set; }
    }
}
