//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_send
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_send()
        {
            this.tb_check_send = new HashSet<tb_check_send>();
        }
    
        public long SendId { get; set; }
        public string UID { get; set; }
        public string InvoicePack { get; set; }
        public string ResponcePack { get; set; }
        public string CheckPack { get; set; }
        public string SendDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<long> ClientID { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_check_send> tb_check_send { get; set; }
        public virtual User User { get; set; }
    }
}
