//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class toor_TB
    {
        public long toorID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> count_day { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<long> userID { get; set; }
        public Nullable<int> cancel { get; set; }
        public Nullable<int> finish { get; set; }
        public Nullable<int> complete { get; set; }
        public Nullable<long> LocID { get; set; }
        public string makan { get; set; }
        public string saat_start { get; set; }
        public string saat_end { get; set; }
        public string sarparast { get; set; }
        public string tajhizat { get; set; }
        public string servis { get; set; }
        public string tamas { get; set; }
        public string zarfiyat { get; set; }
        public string hazine { get; set; }
        public string type_safar { get; set; }
    
        public virtual Locations_TB Locations_TB { get; set; }
        public virtual user_TB user_TB { get; set; }
    }
}
