//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourBookingTripper
    {
        public long Id { get; set; }
        public int BookingId { get; set; }
        public Nullable<long> ToutCostId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NationalCode { get; set; }
        public string NationalCard { get; set; }
    
        public virtual TourAgencyCost TourAgencyCost { get; set; }
        public virtual TourBooking TourBooking { get; set; }
    }
}
