//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourEquipment
    {
        public long Id { get; set; }
        public long TourId { get; set; }
        public int EquipmentId { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
