//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourStop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TourStop()
        {
            this.TourStopLocations = new HashSet<TourStopLocation>();
        }
    
        public long Id { get; set; }
        public long TourId { get; set; }
        public int CityId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public short StopTypeId { get; set; }
        public short StopOrder { get; set; }
        public short Nights { get; set; }
        public Nullable<long> HotelId { get; set; }
        public int TransportCompanyId { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public string DepartureDateFa { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public Nullable<int> DepartureStationId { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public Nullable<int> ArrivalStationId { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public Nullable<System.TimeSpan> WaitDuration { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Location Location { get; set; }
        public virtual LocCity LocCity { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual Tour Tour { get; set; }
        public virtual TourStopType TourStopType { get; set; }
        public virtual TransportCompany TransportCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourStopLocation> TourStopLocations { get; set; }
    }
}
