//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourStopLocation
    {
        public long TourLocationID { get; set; }
        public Nullable<long> TourStopId { get; set; }
        public long LocationID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual TourStop TourStop { get; set; }
    }
}
