//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.AgencyRatings = new HashSet<AgencyRating>();
            this.HotelPackages = new HashSet<HotelPackage>();
            this.TourAgencyCosts = new HashSet<TourAgencyCost>();
            this.TourCheckouts = new HashSet<TourCheckout>();
            this.TourStops = new HashSet<TourStop>();
            this.Coupons = new HashSet<Coupon>();
            this.Equipments = new HashSet<Equipment>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public int TourTypeId { get; set; }
        public int HardnessId { get; set; }
        public int FromCityId { get; set; }
        public int TransportTypeId { get; set; }
        public bool HasHotel { get; set; }
        public string Description { get; set; }
        public short Nights { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int UserId { get; set; }
        public bool IsActive { get; set; }
        public string ImageUrl { get; set; }
        public bool Canceled { get; set; }
        public bool Finished { get; set; }
        public string StartPlace { get; set; }
        public Nullable<int> SupervisorId { get; set; }
        public string SupervisorName { get; set; }
        public string Services { get; set; }
        public string PhoneNumber { get; set; }
        public int Capacity { get; set; }
        public long Budget { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgencyRating> AgencyRatings { get; set; }
        public virtual Hardness Hardness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelPackage> HotelPackages { get; set; }
        public virtual LocCity LocCity { get; set; }
        public virtual TourType TourType { get; set; }
        public virtual TransportType TransportType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourAgencyCost> TourAgencyCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourCheckout> TourCheckouts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourStop> TourStops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coupon> Coupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipments { get; set; }
    }
}
