//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourCheckout
    {
        public long Id { get; set; }
        public long TourId { get; set; }
        public long AgancyQuota { get; set; }
        public long CompanyQuota { get; set; }
        public long Amount { get; set; }
        public int TypeId { get; set; }
        public string AccountNumber { get; set; }
        public string TrackingNumber { get; set; }
        public string Receipt { get; set; }
        public string FileUrl { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual CheckoutType CheckoutType { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
