//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBranch
    {
        public long UserBranchId { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> BrancheID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual User User { get; set; }
    }
}
