//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgencyBankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgencyBankAccount()
        {
            this.TransactionMultiplexings = new HashSet<TransactionMultiplexing>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public int BankId { get; set; }
        public string AccountNumber { get; set; }
        public string Shaba { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionMultiplexing> TransactionMultiplexings { get; set; }
    }
}
