//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgencyRating
    {
        public int Id { get; set; }
        public int AgancyId { get; set; }
        public long TourId { get; set; }
        public int Rating { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Approved { get; set; }
        public int UserId { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual Tour Tour { get; set; }
        public virtual User User { get; set; }
    }
}
