//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int BlogID { get; set; }
        public Nullable<int> BlogTagID { get; set; }
        public string TitleFa { get; set; }
        public string TitleEn { get; set; }
        public string ContentFa { get; set; }
        public string ContentEn { get; set; }
        public string Tag { get; set; }
    
        public virtual BlogTag BlogTag { get; set; }
    }
}
