//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingTransaction()
        {
            this.HotelBookings = new HashSet<HotelBooking>();
            this.Payments = new HashSet<Payment>();
            this.TransactionMultiplexings = new HashSet<TransactionMultiplexing>();
        }
    
        public long Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public long Amount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int BookingTypeId { get; set; }
        public int TransactionTypeId { get; set; }
        public int TerminalId { get; set; }
        public string InvoiceNumber { get; set; }
        public long Discount { get; set; }
        public Nullable<int> CouponId { get; set; }
    
        public virtual BookingType BookingType { get; set; }
        public virtual Terminal Terminal { get; set; }
        public virtual TransactionType TransactionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelBooking> HotelBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionMultiplexing> TransactionMultiplexings { get; set; }
    }
}
