//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelDateCost
    {
        public long Id { get; set; }
        public long HotelId { get; set; }
        public System.DateTime DateEn { get; set; }
        public string DateFa { get; set; }
        public long Cost { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int UserId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
