//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelSpec
    {
        public long HotelId { get; set; }
        public int SpecId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual PlaceSpec PlaceSpec { get; set; }
        public virtual SpecType SpecType { get; set; }
    }
}
