//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locations_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locations_TB()
        {
            this.toor_TB = new HashSet<toor_TB>();
        }
    
        public long LocID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lang { get; set; }
        public string type_loc { get; set; }
        public Nullable<int> weight { get; set; }
        public string ostan { get; set; }
        public string city { get; set; }
        public string rusta { get; set; }
        public string shakhesh { get; set; }
        public string emkanat { get; set; }
        public string dastrasi { get; set; }
        public Nullable<bool> act { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<long> NewLocationId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> AspUserId { get; set; }
    
        public virtual LocCity LocCity { get; set; }
        public virtual LocationType LocationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<toor_TB> toor_TB { get; set; }
    }
}
