//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MrTripEntities : DbContext
    {
        public MrTripEntities()
            : base("name=MrTripEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbuseReport> AbuseReports { get; set; }
        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<AgencyRating> AgencyRatings { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<BlogCatagory> BlogCatagories { get; set; }
        public virtual DbSet<BlogTag> BlogTags { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<FacilityType> FacilityTypes { get; set; }
        public virtual DbSet<GlobalMeta> GlobalMetas { get; set; }
        public virtual DbSet<Hardness> Hardnesses { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<HotelBooking> HotelBookings { get; set; }
        public virtual DbSet<HotelComment> HotelComments { get; set; }
        public virtual DbSet<HotelDateCost> HotelDateCosts { get; set; }
        public virtual DbSet<HotelDiscount> HotelDiscounts { get; set; }
        public virtual DbSet<HotelImage> HotelImages { get; set; }
        public virtual DbSet<HotelPackage> HotelPackages { get; set; }
        public virtual DbSet<HotelRoomType> HotelRoomTypes { get; set; }
        public virtual DbSet<HotelService> HotelServices { get; set; }
        public virtual DbSet<HotelSpec> HotelSpecs { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationComment> LocationComments { get; set; }
        public virtual DbSet<LocationGroup> LocationGroups { get; set; }
        public virtual DbSet<LocationImage> LocationImages { get; set; }
        public virtual DbSet<Locations_TB> Locations_TB { get; set; }
        public virtual DbSet<LocationType> LocationTypes { get; set; }
        public virtual DbSet<LocCity> LocCities { get; set; }
        public virtual DbSet<LocCountry> LocCountries { get; set; }
        public virtual DbSet<LocProvince> LocProvinces { get; set; }
        public virtual DbSet<Log_TB> Log_TB { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentResult> PaymentResults { get; set; }
        public virtual DbSet<PaymentResultLog> PaymentResultLogs { get; set; }
        public virtual DbSet<PlaceSpec> PlaceSpecs { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Post_TB> Post_TB { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SpecType> SpecTypes { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<temp> temps { get; set; }
        public virtual DbSet<Terminal> Terminals { get; set; }
        public virtual DbSet<toor_TB> toor_TB { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<TourAgencyCost> TourAgencyCosts { get; set; }
        public virtual DbSet<TourBooking> TourBookings { get; set; }
        public virtual DbSet<TourBookingTripper> TourBookingTrippers { get; set; }
        public virtual DbSet<TourCheckout> TourCheckouts { get; set; }
        public virtual DbSet<TourStop> TourStops { get; set; }
        public virtual DbSet<TourStopType> TourStopTypes { get; set; }
        public virtual DbSet<TourType> TourTypes { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<TransportCompany> TransportCompanies { get; set; }
        public virtual DbSet<TransportType> TransportTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<user_TB> user_TB { get; set; }
        public virtual DbSet<UserSession> UserSessions { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
