//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MrTripEntities : DbContext
    {
        public MrTripEntities()
            : base("name=MrTripEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<TourAgencyCost> TourAgencyCosts { get; set; }
        public virtual DbSet<TourBooking> TourBookings { get; set; }
        public virtual DbSet<TourBookingTripper> TourBookingTrippers { get; set; }
        public virtual DbSet<TourCheckout> TourCheckouts { get; set; }
        public virtual DbSet<TourStop> TourStops { get; set; }
        public virtual DbSet<TourStopType> TourStopTypes { get; set; }
        public virtual DbSet<TourType> TourTypes { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<TransportCompany> TransportCompanies { get; set; }
        public virtual DbSet<TransportType> TransportTypes { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocCity> LocCities { get; set; }
        public virtual DbSet<LocCountry> LocCountries { get; set; }
        public virtual DbSet<LocProvince> LocProvinces { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<Hardness> Hardnesses { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Agency> Agencies { get; set; }
        public virtual DbSet<HotelRoomType> HotelRoomTypes { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<LocationType> LocationTypes { get; set; }
    }
}
