//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string NationalCode { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string DocumentUrl { get; set; }
        public bool IsActive { get; set; }
        public bool IsConfirmed { get; set; }
        public string ConfirmByUserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
