//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_TB
    {
        public long postid { get; set; }
        public string title { get; set; }
        public string matn { get; set; }
        public Nullable<long> userid { get; set; }
        public Nullable<bool> act { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual user_TB user_TB { get; set; }
    }
}
