//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostTag
    {
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
    
        public virtual PostCategory PostCategory { get; set; }
    }
}
