//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RailWayRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RailWayRequest()
        {
            this.RequestLogs = new HashSet<RequestLog>();
            this.RequestPassengers = new HashSet<RequestPassenger>();
            this.RWS = new HashSet<RW>();
            this.RWWs = new HashSet<RWW>();
            this.TicketDetails = new HashSet<TicketDetail>();
            this.TicketInfoes = new HashSet<TicketInfo>();
        }
    
        public int RailWayRequestID { get; set; }
        public Nullable<int> StartStationID { get; set; }
        public Nullable<int> EndStationID { get; set; }
        public Nullable<int> TicketTypeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> RationCode { get; set; }
        public Nullable<int> SexCode { get; set; }
        public Nullable<int> TicketCount { get; set; }
        public Nullable<bool> CoupeDoor { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> DoneID { get; set; }
        public Nullable<System.TimeSpan> LimitTime { get; set; }
        public Nullable<int> RequestTypeID { get; set; }
        public Nullable<int> TripTypeID { get; set; }
        public Nullable<int> AlternativeSexCode { get; set; }
        public string message { get; set; }
        public Nullable<int> ParentRailWayRequestID { get; set; }
    
        public virtual Done Done { get; set; }
        public virtual RequestType RequestType { get; set; }
        public virtual Sex Sex { get; set; }
        public virtual RailWayStation RailWayStation { get; set; }
        public virtual RailWayStation RailWayStation1 { get; set; }
        public virtual TicketType TicketType { get; set; }
        public virtual TripType TripType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestLog> RequestLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestPassenger> RequestPassengers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RW> RWS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RWW> RWWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketDetail> TicketDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketInfo> TicketInfoes { get; set; }
    }
}
