//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RailWayBot
    {
        public int ID { get; set; }
        public bool Disconnect { get; set; }
        public bool Stop { get; set; }
        public bool RestartService { get; set; }
        public bool CheckAnydesk { get; set; }
    }
}
