//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestPassenger
    {
        public int RequestPassengerID { get; set; }
        public Nullable<long> PassengerID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> RailWayRequestID { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual PassengerService PassengerService { get; set; }
        public virtual RailWayRequest RailWayRequest { get; set; }
    }
}
