//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RW
    {
        public int ID { get; set; }
        public Nullable<int> RailWayRequestID { get; set; }
        public Nullable<int> SchedulingID { get; set; }
        public Nullable<int> GoReturnID { get; set; }
        public Nullable<int> Priority { get; set; }
    
        public virtual GoReturn GoReturn { get; set; }
        public virtual RailWayRequest RailWayRequest { get; set; }
        public virtual Scheduling Scheduling { get; set; }
    }
}
