//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RWW
    {
        public int WID { get; set; }
        public Nullable<int> WRailWayRequestID { get; set; }
        public Nullable<int> WSchedulingID { get; set; }
        public Nullable<int> WWagonTypeID { get; set; }
        public Nullable<int> WPriority { get; set; }
    
        public virtual RailWayRequest RailWayRequest { get; set; }
        public virtual Scheduling Scheduling { get; set; }
        public virtual Wagon Wagon { get; set; }
    }
}
