//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheduling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scheduling()
        {
            this.RWS = new HashSet<RW>();
            this.RWWs = new HashSet<RWW>();
            this.SWTs = new HashSet<SWT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> StartStationID { get; set; }
        public Nullable<int> EndStationID { get; set; }
        public Nullable<System.TimeSpan> StartStationMovingTime { get; set; }
        public Nullable<System.TimeSpan> EndStationArrivalTime { get; set; }
        public Nullable<int> TrainNumber { get; set; }
    
        public virtual RailWayStation RailWayStation { get; set; }
        public virtual RailWayStation RailWayStation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RW> RWS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RWW> RWWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SWT> SWTs { get; set; }
    }
}
