//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketDetail
    {
        public long ID { get; set; }
        public Nullable<int> RailWayRequestID { get; set; }
        public string SellSerial { get; set; }
        public string Row { get; set; }
        public string TrackId { get; set; }
        public string FromStationName { get; set; }
        public string ExitDate { get; set; }
        public string ExitDay { get; set; }
        public string TrainNo { get; set; }
        public string ToStationName { get; set; }
        public string PassengerName { get; set; }
        public string WagonName { get; set; }
        public string ExitTime { get; set; }
        public string WagonNo { get; set; }
        public string SeatNo { get; set; }
        public string ArriveTime { get; set; }
        public string TicketPrice { get; set; }
        public string DiscountAmount { get; set; }
        public string Issuer { get; set; }
        public string StationServices { get; set; }
        public string TotalPrice { get; set; }
        public Nullable<bool> CancelRequest { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
    
        public virtual RailWayRequest RailWayRequest { get; set; }
    }
}
