//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketInfo
    {
        public long ID { get; set; }
        public Nullable<int> RailWayRequestID { get; set; }
        public string SellSerial { get; set; }
        public string FromStationName { get; set; }
        public string ToStationName { get; set; }
        public string ShExiteDate { get; set; }
        public string ExiteTime { get; set; }
        public string Degree { get; set; }
        public string WagonNo { get; set; }
        public string CompartmentNo { get; set; }
        public string SexName { get; set; }
        public string TrainNo { get; set; }
        public string WagonTypeName { get; set; }
        public string RationName { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.Guid> TrackID { get; set; }
    
        public virtual RailWayRequest RailWayRequest { get; set; }
    }
}
