//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourAgencyCost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TourAgencyCost()
        {
            this.TourBookingTrippers = new HashSet<TourBookingTripper>();
        }
    
        public long Id { get; set; }
        public long TourId { get; set; }
        public int AgencyId { get; set; }
        public short RoomTypeId { get; set; }
        public long Price { get; set; }
        public long UserDiscount { get; set; }
        public long AffiliateDiscount { get; set; }
        public long FullDiscount { get; set; }
        public Nullable<int> PackageNumber { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public long CurrencyPrice { get; set; }
    
        public virtual Tour Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TourBookingTripper> TourBookingTrippers { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Agency Agency { get; set; }
        public virtual HotelRoomType HotelRoomType { get; set; }
    }
}
