//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionMultiplexing
    {
        public long Id { get; set; }
        public long TransactionId { get; set; }
        public Nullable<long> FullAmount { get; set; }
        public int AgencyId { get; set; }
        public int AgencyAccountId { get; set; }
        public long AgencyShare { get; set; }
        public long SiteShareOne { get; set; }
        public long SiteShareTwo { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual AgencyBankAccount AgencyBankAccount { get; set; }
        public virtual BookingTransaction BookingTransaction { get; set; }
    }
}
