//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_TB()
        {
            this.CommentPost_TB = new HashSet<CommentPost_TB>();
            this.Comments_TB = new HashSet<Comments_TB>();
            this.fav_TB = new HashSet<fav_TB>();
            this.Post_TB = new HashSet<Post_TB>();
            this.smsCodes = new HashSet<smsCode>();
            this.toor_TB = new HashSet<toor_TB>();
        }
    
        public long userID { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string tel { get; set; }
        public string pass { get; set; }
        public string type { get; set; }
        public string GroupRasmi { get; set; }
        public string faaliyat { get; set; }
        public string GroupName { get; set; }
        public string sabt { get; set; }
        public string ostan { get; set; }
        public string city { get; set; }
        public string semat { get; set; }
        public string emtiyaz { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<bool> act { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentPost_TB> CommentPost_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments_TB> Comments_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fav_TB> fav_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post_TB> Post_TB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<smsCode> smsCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<toor_TB> toor_TB { get; set; }
    }
}
