//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Locations = new HashSet<Location>();
            this.Tours = new HashSet<Tour>();
            this.Tours1 = new HashSet<Tour>();
            this.Roles = new HashSet<Role>();
            this.Agencies = new HashSet<Agency>();
            this.Coupons = new HashSet<Coupon>();
        }
    
        public int Id { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int TypeId { get; set; }
        public string AgencyName { get; set; }
        public string PermitNumber { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<bool> IsMountainClimbingClub { get; set; }
        public Nullable<bool> PermitTypeA { get; set; }
        public Nullable<bool> PermitTypeB { get; set; }
        public Nullable<bool> PermitTypeP { get; set; }
        public string ImageUrl { get; set; }
        public string GuideNumber { get; set; }
        public Nullable<bool> IsLocalGuide { get; set; }
        public string LocalGuideCardUrl { get; set; }
        public Nullable<bool> IsCulturalGuide { get; set; }
        public string CulturalGuideCardUrl { get; set; }
        public string OtherLanguage { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ConfirmationCode { get; set; }
        public Nullable<long> OldUserId { get; set; }
        public Nullable<bool> AgencyConfirmed { get; set; }
        public Nullable<bool> GuideConfirmed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Locations { get; set; }
        public virtual LocProvince LocProvince { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tours1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
        public virtual UserType UserType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agency> Agencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coupon> Coupons { get; set; }
    }
}
