//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTax.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wagon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wagon()
        {
            this.RWWs = new HashSet<RWW>();
            this.SWTs = new HashSet<SWT>();
        }
    
        public int WagonTypeID { get; set; }
        public string WagonName { get; set; }
        public Nullable<int> WagonType { get; set; }
        public Nullable<int> Degree { get; set; }
        public Nullable<int> CompartmentCapicity { get; set; }
        public Nullable<long> Cost { get; set; }
        public Nullable<long> FullPrice { get; set; }
        public Nullable<int> RateCode { get; set; }
        public Nullable<int> ownerWagon { get; set; }
        public string ownerName { get; set; }
        public Nullable<bool> AirConditioning { get; set; }
        public Nullable<bool> Media { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RWW> RWWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SWT> SWTs { get; set; }
    }
}
